# Generated by Django 2.2.6 on 2019-11-28 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Event Name')),
                ('date_act', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 561839, tzinfo=utc))),
                ('supplier_name', models.CharField(max_length=120, verbose_name='Supplier Name')),
                ('adress', models.CharField(max_length=500, verbose_name='Google Map ID')),
                ('budget', models.FloatField(default=0)),
                ('real_price', models.FloatField(default=0)),
                ('cancelation_policy_deadline', models.PositiveIntegerField()),
                ('cancelation_policy_fees', models.FloatField()),
                ('contact_name', models.CharField(max_length=120, verbose_name='Contact Name')),
                ('phone_number', models.CharField(max_length=120, verbose_name='Event Name')),
                ('mail_adress', models.EmailField(default='a@ext.com', max_length=254)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('cf', 'Cancelled and factured'), ('cnf', 'Cancelled and not factured'), ('f', 'Factured'), ('cn', 'Cancelled and negociated')], max_length=10)),
                ('typ_act', models.CharField(choices=[('1', 'Beauté'), ('2', 'Santé'), ('3', 'Bar'), ('4', 'Arts'), ('5', 'Autre')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Driver Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Driver Last Name')),
                ('langue', models.CharField(max_length=120, verbose_name='Client Language')),
                ('lieu_depart', models.TextField(blank=True)),
                ('lieu_arrivee', models.TextField(blank=True)),
                ('consigne', models.TextField(blank=True)),
                ('photo', models.BooleanField(default=False)),
                ('horaire_chauffeur', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 571778, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Event Name')),
                ('date_debut', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 560809, tzinfo=utc))),
                ('date_fin', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 560809, tzinfo=utc))),
                ('description', models.TextField(blank=True)),
                ('place', models.CharField(max_length=120, verbose_name='Event Place')),
            ],
        ),
        migrations.CreateModel(
            name='Fashion_House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_name', models.CharField(max_length=120, verbose_name='Fashion House Name')),
                ('debrief_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_nb', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 571778, tzinfo=utc))),
                ('date_fin', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 571778, tzinfo=utc))),
                ('room_type', models.CharField(max_length=120, verbose_name='Hotel Name')),
                ('cancellation', models.BooleanField(default=False)),
                ('tarif', models.FloatField(default=0)),
                ('estimated_budget', models.FloatField(default=0)),
                ('paid_by_JP', models.FloatField(default=0)),
                ('paid_by_client', models.FloatField(default=0)),
                ('night_booked_jp', models.PositiveIntegerField(default=0)),
                ('night_booked_client', models.PositiveIntegerField(default=0)),
                ('welcome_pack_arrived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights_booked', models.PositiveIntegerField(default=0)),
                ('digital_planning', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=120, verbose_name='Client Language')),
                ('travel_fees', models.FloatField(default=0)),
                ('list_activities', models.ManyToManyField(to='core.Activity', verbose_name='list of activities')),
                ('list_driver', models.ManyToManyField(to='core.Chauffeur', verbose_name='list of drivers')),
                ('list_hotel', models.ManyToManyField(to='core.Hotel', verbose_name='list of hotels')),
            ],
        ),
        migrations.CreateModel(
            name='One_to_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 32, 33, 561839, tzinfo=utc))),
                ('salon', models.PositiveIntegerField(default=0)),
                ('staff', models.TextField(blank=True)),
                ('title', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Event associated to')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='fashion_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Fashion_House', verbose_name='Fashion House Name'),
        ),
        migrations.CreateModel(
            name='Concierge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=120, verbose_name='ID')),
                ('mdp', models.CharField(max_length=120, verbose_name='Password')),
                ('name', models.CharField(max_length=120, verbose_name='Concierge Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Concierge Last Name')),
                ('list_events', models.ManyToManyField(default=0, to='core.Event', verbose_name='list of events')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Client Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Client Last Name')),
                ('zone', models.CharField(max_length=120, verbose_name='Market Place')),
                ('contact_principal', models.EmailField(default='test@jp.com', max_length=254)),
                ('langue', models.CharField(max_length=120, verbose_name='Client Language')),
                ('accompanied', models.BooleanField(default=False)),
                ('budget_jour', models.FloatField(default=0)),
                ('budget_semaine', models.FloatField(default=0)),
                ('date', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.One_to_One', verbose_name='Date of the One to One')),
                ('plan', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Planning')),
                ('title', models.ManyToManyField(to='core.Event', verbose_name='list of events')),
            ],
        ),
    ]
