# Generated by Django 2.2.6 on 2019-11-28 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_act',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 200771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='horaire_chauffeur',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 207953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 198776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 198776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 208951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 208951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='one_to_one',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 17, 39, 43, 199773, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Hospitality_Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.TextField(blank=True)),
                ('horaires_dispo_concierge', models.TextField(blank=True)),
                ('welcome_pack', models.TextField(blank=True)),
                ('list_services', models.ManyToManyField(to='core.Activity', verbose_name='list of activities')),
                ('title', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
