# Generated by Django 2.2.6 on 2019-12-01 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191128_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_act',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 517006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='horaire_chauffeur',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 527007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 516007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 516007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 528006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 528006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='one_to_one',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 20, 49, 57, 517006, tzinfo=utc)),
        ),
    ]
