# Generated by Django 2.2.6 on 2019-12-02 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191202_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_act',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='horaire_chauffeur',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_arrival',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 646832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_leave',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 646832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='one_to_one',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 12, 23, 32, 631208, tzinfo=utc)),
        ),
    ]
